Deleting Comments and Test Anchors
Security-Onion-Solutions/securityonion-soc pull request #389
Opened 2024-03-15 19:10 UTC by coreyogburn

Comments can now be deleted. We were passing in a crossclustered index when a non-remote index was expected.

In order to facilitate cypress tests, a couple IDs were added.

2024-03-15 19:59 UTC, coreyogburn commented
Somehow comments were getting deleted without getting audited. Added that to this PR as well.

2024-03-15 20:07 UTC, jertel approved these changes, later dismissed

2024-03-20 15:22 UTC, jertel requested changes

2024-03-20 15:22 UTC, jertel commented on html/js/routes/detection.js
> +				this.$root.stopLoading();
This one may not be needed since it's already called in the finally{} block

2024-03-20 15:22 UTC, jertel commented on server/modules/elastic/elasticdetectionstore.go
> +			"kind":       kind,
This field should be `detectionKind` to avoid log ingest field type collisions with unrelated log lines.

2024-03-20 16:35 UTC, jertel approved these changes

2024-03-20 16:36 UTC, merged